#!/usr/bin/env python3
"""Build the Symantec API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Symantec Security',
        "color": '#FDB511',
        "closed": True,
        "stations": [
        ('SEPM', (640, 260)),
        ('SES', (840, 460)),
        ('EDR', (640, 660)),
        ('DLP', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'SEPM': 'https://apis.apis.io/apis/symantec/sepm-api/',
    'SES': 'https://apis.apis.io/apis/symantec/ses-api/',
    'EDR': 'https://apis.apis.io/apis/symantec/symantec-edr-api/',
    'DLP': 'https://apis.apis.io/apis/symantec/symantec-dlp-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Symantec API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: symantec/openapi · github.com/api-evangelist/symantec',
        out_dir=Path(__file__).resolve().parent,
        out_basename='symantec-subway-map',
        provider_id='symantec',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
